SERVER=server
SUBSCRIBER=subscriber
PROJECT=$(SERVER) $(SUBSCRIBER)

SOURCES_SERVER=server.cpp
SOURCES_SUBSCRIBER=subscriber.cpp
SOURCES=$(SOURCES_SERVER) $(SOURCES_SUBSCRIBER)

LDFLAGS=
CFLAGS=-c -Wall -Werror -Wno-error=unused-variable
CC=g++

OBJECTS_SERVER=$(SOURCES_SERVER:.cpp=.o)
OBJECTS_SUBSCRIBER=$(SOURCES_SUBSCRIBER:.cpp=.o)
OBJECTS=$(OBJECTS_SERVER) $(OBJECTS_SUBSCRIBER)

BINARY=$(PROJECT)

all: $(SOURCES) $(BINARY)

$(SERVER): $(OBJECTS_SERVER)
	$(CC) $(OBJECTS_SERVER) $(LDFLAGS) -o $@

$(SUBSCRIBER): $(OBJECTS_SUBSCRIBER)
	$(CC) $(OBJECTS_SUBSCRIBER) $(LDFLAGS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) -fPIC $< -o $@

clean:
	rm -rf $(OBJECTS) $(PROJECT)

.PHONY: all clean
